# runtime: python
# entrypoint: gunicorn -b :8080 main:app
# runtime_config:
#   python_version: 3
runtime: custom
env: flex

readiness_check:
  app_start_timeout_sec: 1800

# instance_class: F4_HIGHMEM
manual_scaling:
  instances: 2

resources:
  cpu: 8
  memory_gb: 32
  disk_size_gb: 10


handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto